name: clang-tidy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install clang-19 clang-tools-19 clang-tidy-19 cmake ninja-build

    - name: Configure build
      run: |
        cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-19 -DCRC_TEST=ON -DCRC_MODULE=ON -DCRC_BENCHMARK=ON

    - name: Build
      run: |
        cmake --build build

    - name: Run clang-tidy
      run: |
        clang-tidy-19 --warnings-as-errors="*" -p build test/*.cpp benchmark/*.cpp src/*.cppm include/crc/*.hpp
