name: clang-tidy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
    llvm_version: 21

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{env.llvm_version}}
        sudo apt-get update
        sudo apt-get install clang-tidy-${{env.llvm_version}} cmake ninja-build

    - name: Configure build
      run: |
        cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-${{env.llvm_version}} -DZCRC_TEST=ON -DZCRC_BENCHMARK=ON

    - name: Build
      run: |
        cmake --build build

    - name: Run clang-tidy
      run: |
        clang-tidy-${{env.llvm_version}} --warnings-as-errors="*" -p build test/*.cpp benchmark/*.cpp include/zcrc/*.hpp
